version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=usuario_db
      - POSTGRES_PASSWORD=password_super_secreto
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    environment:
      - POSTGES_NAME=django_db
      - POSTGRES_USER=usuario_db
      - POSTGRES_PASSWORD=password_super_secreto
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: