# Usar una imagen oficial de Python como base
FROM python:3.11-slim

# Evitar que Python genere archivos .pyc y obligar a que la salida de la terminal sea en tiempo real
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de requerimientos e instalarlos
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copiar el resto del código del proyecto al contenedor
COPY . /app/