# Generated by Django 4.2.30 on 2026-06-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Salon')),
                ('edificio', models.CharField(max_length=50, unique=True, verbose_name='Edificio')),
                ('capacidad', models.IntegerField()),
                ('largo', models.FloatField()),
                ('ancho', models.FloatField()),
                ('altura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VariableAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('iluminacion', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_de_Monitoreo.salon')),
            ],
        ),
    ]
